# ***************** Universidad de los Andes ***********************
# ****** Departamento de Ingeniería de Sistemas y Computación ******
# ********** Arquitectura y diseño de Software - ISIS2503 **********
#
# Infraestructura para laboratorio de microservicios con Django
# Elementos a desplegar:
# 1. Firewalls:
#    - msd-api-gateway
#    - msd-services-apps
#    - msd-services-apps-web
#    - msd-service-db
# 2. Instancias MVs:
#    - msd-kong-instance
#    - msd-variables-db (postgreSQL instalado y configurado)
#    - msd-measurements-db (postgreSQL instalado y configurado)
#    - msd-variables-ms (Servicio de variables descargado)
#    - msd-measurements-ms (Servicio de measurements instalado y configurado)

resources:
- name: msd-places-db
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/healthy-firefly-415316/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/cos-cloud/global/images/cos-101-17162-463-8
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/healthy-firefly-415316/global/networks/default
      networkIP: 10.128.0.86
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items: 
      - msd-service-db
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          docker run --restart=always -d -e POSTGRES_USER=places_user -e POSTGRES_DB=places_db -e POSTGRES_PASSWORD=isis2503 -p 5432:5432 --name places-db postgres


- name: msd-places-ms
  type: compute.v1.instance
  properties:
    zone: us-central1-a
    machineType: https://www.googleapis.com/compute/v1/projects/healthy-firefly-415316/zones/us-central1-a/machineTypes/e2-micro
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: https://www.googleapis.com/compute/v1/projects/cos-cloud/global/images/cos-101-17162-463-8
    networkInterfaces:
    - network: https://www.googleapis.com/compute/v1/projects/healthy-firefly-415316/global/networks/default
      networkIP: 10.128.0.87
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items: 
      - msd-services-firewall
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          sudo mkdir /home/labs
          cd /home/labs
          sudo git clone https://github.com/RuizL25/lab-microservicios.git
          cd lab-microservicios/places

